api_platform:
  title: Haraka API Platform
  version: 1.0.0
  formats:
    jsonld: ["application/ld+json"]
    json: ["application/json"]
    multipart: ["multipart/form-data"]
  defaults:
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
    pagination_client_items_per_page: true
    pagination_items_per_page: 12
    pagination_maximum_items_per_page: 50

  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
