vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    student_image:
      uri_prefix: /picture/students/image
      upload_destination: "%kernel.project_dir%/public/picture/students/image"
      # Will rename uploaded files using a uniqueid as a prefix.
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    payment_method_image:
      uri_prefix: /picture/payment-method/
      upload_destination: "%kernel.project_dir%/public/picture/payment-method"
      # Will rename uploaded files using a uniqueid as a prefix.
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
