services:
  - type: web
    name: symfony-app
    plan: free
    buildCommand: "composer install"
    startCommand: "php -S 0.0.0.0:8000 -t public"
    envVars:
      - key: APP_ENV
        value: production
      - key: DATABASE_URL
        value: mysql://user:password@host:port/dbname
